config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :users
  resources :products do
    resources :comments
  end 
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/index'
  get 'static_pages/landing_page'
  post 'static_pages/thank_you'
  post 'payments/create'
  root 'static_pages#landing_page'
  resources :orders, only: [:index, :show, :create, :destroy]
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Brandon's Bikes</title>
  <%= csrf_meta_tags %>

  <!-- Link Bootstrap -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= favicon_link_tag %>
</head>

<body>
  <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to("Home", static_pages_index_path) %></li>
          <li><%= link_to("Products", products_path) %></li>
          <li><%= link_to("Contact", static_pages_contact_path) %></li>
          <li><%= link_to("About", static_pages_about_path) %></li>
          <li><!-- Search Form -->
            <%= form_tag("/products", method: "get", class: "form-inline navbar-form hidden-sm", role: "search") do %>
              <div class="form-group">
                <%= label_tag(:q, "Find a bike:", class: "sr-only") %>
                <%= text_field_tag(:q, nil, class: "form-control search-box") %>
              </div>
              <%= submit_tag("Search", class: "btn btn-default") %>
            <% end %>
          </li>
        </ul>
        
        <!-- User Auth Features -->
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li>
              <%= link_to('My Account', edit_user_path(current_user), class: "nav-link") %>
            </li>
          <% end %>  
          <li>
            <% if user_signed_in? %>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete, class: "nav-link") %>
            <% else %>
              <%= link_to('Login', new_user_session_path, class: "nav-link") %>
            <% end %>
          </li>
        </ul>
        
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <% if notice %>
    <p class="notice alert alert-warning", role="alert"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger", role="alert"><%= alert %></p>
  <% end %>

  <%= yield %>

  <footer>
    &copy; <%= Time.new.year %> Brandon's Bike Shop
  </footer>
</body>

</html>